import yaml from 'js-yaml';
import { writeFileSync, mkdirSync, realpathSync, lstatSync, renameSync, unlinkSync } from 'node:fs';
import { resolve, join } from 'node:path';
import type { ScannedModule } from '../types.js';
import { annotationsToDict } from '../serializers.js';
import type { WriteResult } from './types.js';
import { createWriteResult } from './types.js';
import { WriteError } from './errors.js';
import { YAMLVerifier } from './verifiers.js';
import { applyVerification } from './base-writer.js';
import type { FileWriteOptions } from './base-writer.js';

/**
 * Write scanned modules as YAML binding files.
 *
 * Each module is serialised to a `<module_id>.binding.yaml` file in the
 * specified output directory. The YAML format conforms to the apcore binding
 * spec (`spec_version: "1.0"`).
 */
export class YAMLWriter {
  /**
   * Serialise modules to YAML and write them to `outputDir`.
   *
   * @param modules - Scanned modules to write.
   * @param outputDir - Directory to write binding files into (created if absent).
   * @param options - Optional write options: `dryRun`, `verify`, `verifiers`.
   * @returns Array of WriteResult, one per module.
   */
  write(
    modules: ScannedModule[],
    outputDir: string,
    options?: FileWriteOptions,
  ): WriteResult[] {
    const dryRun = options?.dryRun ?? false;
    const shouldVerify = options?.verify ?? false;
    const verifiers = options?.verifiers ?? [];
    const errorMode = options?.errorMode ?? 'throw';

    if (modules.length === 0) {
      return [];
    }

    const outputPath = resolve(outputDir);

    if (!dryRun) {
      try {
        mkdirSync(outputPath, { recursive: true });
      } catch (err) {
        throw new WriteError(outputPath, err);
      }
    }

    let realOutputPath = outputPath;
    if (!dryRun) {
      try {
        realOutputPath = realpathSync(outputPath);
      } catch (err) {
        throw new WriteError(outputPath, err);
      }
    }

    const results: WriteResult[] = [];
    const timestamp = new Date().toISOString();
    const writtenIds = new Map<string, string>(); // filename → moduleId that claimed it

    for (const module of modules) {
      const bindingData = this._buildBinding(module);

      if (dryRun) {
        results.push(createWriteResult(module.moduleId, null));
        continue;
      }

      let safeId = module.moduleId.replace(/[^a-zA-Z0-9._-]/g, '_');
      safeId = safeId.replace(/\.{2,}/g, '_');
      const baseFilename = `${safeId}.binding.yaml`;
      let filename = baseFilename;
      let collisionCounter = 0;
      while (writtenIds.has(filename)) {
        collisionCounter++;
        filename = `${safeId}_${collisionCounter}.binding.yaml`;
      }
      if (collisionCounter > 0) {
        console.warn(
          'YAMLWriter: safeId collision — "%s" and "%s" both map to %s; using %s',
          writtenIds.get(baseFilename),
          module.moduleId,
          baseFilename,
          filename,
        );
      }
      writtenIds.set(filename, module.moduleId);
      // Build filePath from the real (symlink-resolved) output dir so the
      // prefix check below compares canonical paths on both sides.
      const filePath = resolve(join(realOutputPath, filename));

      // Block pre-existing symlinks at the target path (TOCTOU mitigation).
      try {
        if (lstatSync(filePath).isSymbolicLink()) {
          console.warn('Skipping symlink escape at: %s', filePath);
          results.push(createWriteResult(module.moduleId, filePath, false, 'Security skip: symlink at target path'));
          continue;
        }
      } catch { /* file does not exist — safe to write */ }

      const header =
        `# Auto-generated by apcore-toolkit scanner\n` +
        `# Generated: ${timestamp}\n` +
        `# Do not edit manually unless you intend to customize schemas.\n\n`;

      const yamlContent = yaml.dump(bindingData, {
        flowLevel: -1,
        sortKeys: false,
      });

      // Atomic write via tmp file + rename.
      const tmpPath = `${filePath}.${process.pid}.tmp`;
      try {
        writeFileSync(tmpPath, header + yamlContent, 'utf-8');
        renameSync(tmpPath, filePath);
        // Post-rename sanity check: verify the result is not a symlink (defence-in-depth).
        try {
          if (lstatSync(filePath).isSymbolicLink()) {
            console.warn('YAMLWriter: post-rename symlink detected at %s — possible race', filePath);
          }
        } catch { /* lstat failing here is non-critical */ }
      } catch (err) {
        try { unlinkSync(tmpPath); } catch { /* best-effort cleanup */ }
        if (errorMode === 'collect') {
          results.push(createWriteResult(module.moduleId, filePath, false, err instanceof Error ? err.message : String(err)));
          continue;
        }
        throw new WriteError(filePath, err);
      }

      const result = applyVerification(
        createWriteResult(module.moduleId, filePath),
        new YAMLVerifier(),
        verifiers,
        filePath,
        module.moduleId,
        shouldVerify,
      );
      results.push(result);
    }

    return results;
  }

  private _buildBinding(module: ScannedModule): Record<string, unknown> {
    const binding: Record<string, unknown> = {
      module_id: module.moduleId,
      target: module.target,
      description: module.description,
      documentation: module.documentation,
      tags: [...module.tags],
      version: module.version,
      annotations: annotationsToDict(module.annotations),
      examples: module.examples.length > 0
        ? module.examples.map((e) => structuredClone(e))
        : [],
      metadata: structuredClone(module.metadata),
      input_schema: structuredClone(module.inputSchema),
      output_schema: structuredClone(module.outputSchema),
    };
    if (module.suggestedAlias !== null) {
      binding.suggested_alias = module.suggestedAlias;
    }
    if (module.display !== null) {
      binding.display = structuredClone(module.display);
    }
    return {
      spec_version: "1.0",
      bindings: [binding],
    };
  }
}
