import yaml from 'js-yaml';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { resolve, join, sep } from 'node:path';
import type { ScannedModule } from '../types.js';
import { annotationsToDict } from '../serializers.js';
import type { WriteResult } from './types.js';
import { createWriteResult } from './types.js';
import { WriteError } from './errors.js';
import { YAMLVerifier } from './verifiers.js';
import { applyVerification } from './base-writer.js';
import type { FileWriteOptions } from './base-writer.js';

/**
 * Write scanned modules as YAML binding files.
 *
 * Each module is serialised to a `<module_id>.binding.yaml` file in the
 * specified output directory. The YAML format conforms to the apcore binding
 * spec (`spec_version: "1.0"`).
 */
export class YAMLWriter {
  /**
   * Serialise modules to YAML and write them to `outputDir`.
   *
   * @param modules - Scanned modules to write.
   * @param outputDir - Directory to write binding files into (created if absent).
   * @param options - Optional write options: `dryRun`, `verify`, `verifiers`.
   * @returns Array of WriteResult, one per module.
   */
  write(
    modules: ScannedModule[],
    outputDir: string,
    options?: FileWriteOptions,
  ): WriteResult[] {
    const dryRun = options?.dryRun ?? false;
    const shouldVerify = options?.verify ?? false;
    const verifiers = options?.verifiers ?? [];
    const errorMode = options?.errorMode ?? 'throw';

    if (modules.length === 0) {
      return [];
    }

    const outputPath = resolve(outputDir);

    if (!dryRun) {
      mkdirSync(outputPath, { recursive: true });
    }

    const results: WriteResult[] = [];
    const timestamp = new Date().toISOString();

    for (const module of modules) {
      const bindingData = this._buildBinding(module);

      if (dryRun) {
        results.push(createWriteResult(module.moduleId, null));
        continue;
      }

      let safeId = module.moduleId.replace(/[^a-zA-Z0-9._-]/g, '_');
      safeId = safeId.replace(/\.{2,}/g, '_');
      const filename = `${safeId}.binding.yaml`;
      const filePath = resolve(join(outputPath, filename));

      // Path traversal protection: both outputPath and filePath are resolve()d
      // (normalizes `.` / `..` segments). The sep suffix prevents foo/bar from
      // matching foo/barbaz. Note: resolve() does not dereference symlinks —
      // a symlink inside outputPath pointing outside is not caught here.
      const normalizedOutput = outputPath.endsWith(sep) ? outputPath : outputPath + sep;
      if (!filePath.startsWith(normalizedOutput)) {
        console.warn('Skipping file outside output directory: %s', filePath);
        continue;
      }

      if (existsSync(filePath)) {
        console.warn('Overwriting existing file: %s', filePath);
      }

      const header =
        `# Auto-generated by apcore-toolkit scanner\n` +
        `# Generated: ${timestamp}\n` +
        `# Do not edit manually unless you intend to customize schemas.\n\n`;

      const yamlContent = yaml.dump(bindingData, {
        flowLevel: -1,
        sortKeys: false,
      });

      try {
        writeFileSync(filePath, header + yamlContent, 'utf-8');
      } catch (err) {
        if (errorMode === 'collect') {
          results.push(createWriteResult(module.moduleId, filePath, false, (err as Error).message));
          continue;
        }
        throw new WriteError(filePath, err as Error);
      }

      const result = applyVerification(
        createWriteResult(module.moduleId, filePath),
        new YAMLVerifier(),
        verifiers,
        filePath,
        module.moduleId,
        shouldVerify,
      );
      results.push(result);
    }

    return results;
  }

  private _buildBinding(module: ScannedModule): Record<string, unknown> {
    const binding: Record<string, unknown> = {
      module_id: module.moduleId,
      target: module.target,
      description: module.description,
      documentation: module.documentation,
      tags: [...module.tags],
      version: module.version,
      annotations: annotationsToDict(module.annotations),
      examples: module.examples.length > 0
        ? module.examples.map((e) => structuredClone(e))
        : [],
      metadata: structuredClone(module.metadata),
      input_schema: structuredClone(module.inputSchema),
      output_schema: structuredClone(module.outputSchema),
    };
    if (module.suggestedAlias !== null) {
      binding.suggested_alias = module.suggestedAlias;
    }
    if (module.display !== null) {
      binding.display = structuredClone(module.display);
    }
    return {
      spec_version: "1.0",
      bindings: [binding],
    };
  }
}
